//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaControlDeTrabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato()
        {
            this.Mantenimiento = new HashSet<Mantenimiento>();
        }
    
        public int CodContrato { get; set; }
        public int NroContrato { get; set; }
        public System.DateTime FechaFirma { get; set; }
        public int CodCliente { get; set; }
        public int CodTipoGenerador { get; set; }
        public string NroSerieEquipo { get; set; }
        public int CodCiudadUbicacion { get; set; }
        public System.DateTime FechaFinContrato { get; set; }
        public System.DateTime FechaUltimoMatenimiento { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual TipoGenerador TipoGenerador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mantenimiento> Mantenimiento { get; set; }
    }
}
