//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaControlDeTrabajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        public int CodMatenimiento { get; set; }
        public System.DateTime FechaRealizacion { get; set; }
        public int CodContrato { get; set; }
        public int CodEmpleado { get; set; }
        public string DetalleTrabajo { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
